name: suncet_instrument_simulator
channels:
  - conda-forge
  - defaults
dependencies:
  - aiobotocore=2.16.1
  - aiofiles=24.1.0
  - aioftp=0.24.1
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aioitertools=0.12.0
  - aiosignal=1.3.2
  - anyio=4.8.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asciitree=0.3.3
  - asdf=4.0.0
  - asdf-astropy=0.7.0
  - asdf-coordinates-schemas=0.3.0
  - asdf-standard=1.1.1
  - asdf-transform-schemas=0.5.0
  - astropy=7.0.0
  - astropy-base=7.0.0
  - astropy-healpix=1.0.3
  - astropy-iers-data=0.2025.1.6.0.33.42
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - bokeh=3.6.2
  - botocore=1.35.88
  - bottleneck=1.4.2
  - bqplot=0.12.43
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cdflib=1.3.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - cftime=1.6.4
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - coverage=7.6.10
  - cspice=67
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2024.12.1
  - dask-core=2024.12.1
  - dask-expr=1.1.21
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.12.1
  - drms=0.8.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fasteners=0.19
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gast=0.4.0
  - geos=3.13.0
  - gflags=2.2.2
  - glog=0.7.1
  - glymur=0.13.6
  - h11=0.14.0
  - h2=4.1.0
  - h5netcdf=1.4.1
  - h5py=3.12.1
  - hdf4=4.2.15
  - hdf5=1.14.4
  - hpack=4.0.0
  - html5lib=1.1
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - ipydatagrid=1.4.0
  - ipykernel=6.29.5
  - ipython=8.31.0
  - ipywidgets=8.1.5
  - isodate=0.7.2
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jmespath=1.0.1
  - jplephem=2.21
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libcxx=19.1.6
  - libdeflate=1.23
  - libedit=3.1.20240808
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.33.0
  - libgoogle-cloud-storage=2.33.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libparquet=18.1.0
  - libpng=1.6.45
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=19.1.6
  - locket=1.0.0
  - lxml=5.3.0
  - lz4=4.3.3
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mistune=3.1.0
  - mpl_animators=1.2.0
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.5
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numcodecs=0.14.1
  - numpy=2.2.1
  - openjpeg=2.5.3
  - openssl=3.4.0
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parfive=2.1.0
  - parso=0.8.4
  - partd=1.4.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - propcache=0.2.1
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py2vega=0.6.1
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pycparser=2.22
  - pyerfa=2.0.1.5
  - pygments=2.19.1
  - pyobjc-core=10.3.2
  - pyobjc-framework-cocoa=10.3.2
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - pytest=8.3.4
  - pytest-cov=6.0.0
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytz=2024.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.35.1
  - reproject=0.14.1
  - requests=2.32.3
  - requests-file=2.1.0
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - s3fs=2024.12.0
  - scipy=1.15.0
  - semantic_version=2.10.0
  - send2trash=1.8.3
  - setuptools=75.6.0
  - shapely=2.0.6
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spiceypy=6.0.0
  - stack_data=0.6.3
  - sunpy=6.0.4
  - tblib=3.0.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - xarray=2025.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2024.9.0
  - yaml=0.2.5
  - yarl=1.18.3
  - zarr=2.18.3
  - zeep=4.3.1
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
    - construct==2.10.70
    - imageio-ffmpeg==0.6.0
    - pillow-jpls==1.3.2
    - seaborn==0.13.2
